import type { Patient, DashboardStats, Notification } from '../types';

export const mockPatients: Patient[] = [
  {
    id: 'P001',
    name: 'Eleanor Whitfield',
    age: 67,
    gender: 'Female',
    condition: 'Cardiac Arrhythmia',
    status: 'Critical',
    ward: 'Cardiology — ICU',
    doctor: 'Dr. Rajesh Mehta',
    admittedDate: '2026-03-12',
    lastVisit: '2026-03-19',
    bloodType: 'A+',
    phone: '+1 (555) 210-4892',
    email: 'e.whitfield@email.com',
    vitals: { heartRate: 112, bloodPressure: '148/95', temperature: 38.4, oxygen: 92 },
    avatar: 'EW',
  },
  {
    id: 'P002',
    name: 'Marcus Chen',
    age: 45,
    gender: 'Male',
    condition: 'Type 2 Diabetes',
    status: 'Stable',
    ward: 'Endocrinology — Ward B',
    doctor: 'Dr. Priya Nair',
    admittedDate: '2026-03-15',
    lastVisit: '2026-03-18',
    bloodType: 'O+',
    phone: '+1 (555) 387-2041',
    email: 'm.chen@email.com',
    vitals: { heartRate: 78, bloodPressure: '128/82', temperature: 37.1, oxygen: 98 },
    avatar: 'MC',
  },
  {
    id: 'P003',
    name: 'Sophia Patel',
    age: 32,
    gender: 'Female',
    condition: 'Pneumonia',
    status: 'Improving',
    ward: 'Pulmonology — Ward A',
    doctor: 'Dr. Ananya Krishnan',
    admittedDate: '2026-03-10',
    lastVisit: '2026-03-19',
    bloodType: 'B+',
    phone: '+1 (555) 492-7710',
    email: 's.patel@email.com',
    vitals: { heartRate: 88, bloodPressure: '118/76', temperature: 37.8, oxygen: 95 },
    avatar: 'SP',
  },
  {
    id: 'P004',
    name: 'James Okonkwo',
    age: 58,
    gender: 'Male',
    condition: 'Hypertension',
    status: 'Stable',
    ward: 'General Medicine — Ward C',
    doctor: 'Dr. Vikram Singh',
    admittedDate: '2026-03-17',
    lastVisit: '2026-03-19',
    bloodType: 'AB-',
    phone: '+1 (555) 601-3328',
    email: 'j.okonkwo@email.com',
    vitals: { heartRate: 82, bloodPressure: '140/90', temperature: 36.9, oxygen: 97 },
    avatar: 'JO',
  },
  {
    id: 'P005',
    name: 'Amara Diallo',
    age: 29,
    gender: 'Female',
    condition: 'Appendicitis — Post-op',
    status: 'Improving',
    ward: 'Surgical — Recovery',
    doctor: 'Dr. Suresh Babu',
    admittedDate: '2026-03-16',
    lastVisit: '2026-03-19',
    bloodType: 'O-',
    phone: '+1 (555) 715-9204',
    email: 'a.diallo@email.com',
    vitals: { heartRate: 74, bloodPressure: '112/72', temperature: 37.5, oxygen: 99 },
    avatar: 'AD',
  },
  {
    id: 'P006',
    name: 'Robert Lindqvist',
    age: 74,
    gender: 'Male',
    condition: 'COPD',
    status: 'Critical',
    ward: 'Pulmonology — ICU',
    doctor: 'Dr. Ananya Krishnan',
    admittedDate: '2026-03-08',
    lastVisit: '2026-03-19',
    bloodType: 'A-',
    phone: '+1 (555) 824-6617',
    email: 'r.lindqvist@email.com',
    vitals: { heartRate: 102, bloodPressure: '155/100', temperature: 38.9, oxygen: 88 },
    avatar: 'RL',
  },
  {
    id: 'P007',
    name: 'Fatima Al-Hassan',
    age: 41,
    gender: 'Female',
    condition: 'Kidney Stones',
    status: 'Admitted',
    ward: 'Nephrology — Ward D',
    doctor: 'Dr. Rajesh Mehta',
    admittedDate: '2026-03-18',
    lastVisit: '2026-03-19',
    bloodType: 'B-',
    phone: '+1 (555) 933-5528',
    email: 'f.alhassan@email.com',
    vitals: { heartRate: 91, bloodPressure: '122/80', temperature: 37.2, oxygen: 97 },
    avatar: 'FA',
  },
  {
    id: 'P008',
    name: 'Daniel Kim',
    age: 52,
    gender: 'Male',
    condition: 'Lumbar Disc Herniation',
    status: 'Discharged',
    ward: 'Orthopedics — Ward E',
    doctor: 'Dr. Vikram Singh',
    admittedDate: '2026-03-05',
    lastVisit: '2026-03-17',
    bloodType: 'O+',
    phone: '+1 (555) 042-1193',
    email: 'd.kim@email.com',
    vitals: { heartRate: 70, bloodPressure: '120/78', temperature: 36.6, oxygen: 99 },
    avatar: 'DK',
  },
  {
    id: 'P009',
    name: 'Grace Nakamura',
    age: 63,
    gender: 'Female',
    condition: 'Breast Cancer — Chemo',
    status: 'Stable',
    ward: 'Oncology — Ward F',
    doctor: 'Dr. Priya Nair',
    admittedDate: '2026-03-01',
    lastVisit: '2026-03-19',
    bloodType: 'AB+',
    phone: '+1 (555) 157-8840',
    email: 'g.nakamura@email.com',
    vitals: { heartRate: 76, bloodPressure: '116/74', temperature: 37.0, oxygen: 96 },
    avatar: 'GN',
  },
];

export const mockStats: DashboardStats = {
  totalPatients: 284,
  criticalCases: 12,
  bedsAvailable: 47,
  appointmentsToday: 38,
  recoveryRate: 94.2,
  avgStayDays: 5.8,
};

export const admissionsData = [
  { month: 'Sep', admissions: 198, discharges: 182 },
  { month: 'Oct', admissions: 224, discharges: 210 },
  { month: 'Nov', admissions: 241, discharges: 228 },
  { month: 'Dec', admissions: 210, discharges: 201 },
  { month: 'Jan', admissions: 256, discharges: 238 },
  { month: 'Feb', admissions: 271, discharges: 252 },
  { month: 'Mar', admissions: 284, discharges: 261 },
];

export const wardOccupancyData = [
  { ward: 'Cardiology', occupied: 42, capacity: 50 },
  { ward: 'Pulmonology', occupied: 38, capacity: 45 },
  { ward: 'Oncology', occupied: 55, capacity: 60 },
  { ward: 'General', occupied: 71, capacity: 80 },
  { ward: 'Surgery', occupied: 29, capacity: 40 },
  { ward: 'Ortho', occupied: 22, capacity: 30 },
];

export const conditionDistribution = [
  { name: 'Cardiac', value: 22, color: '#EF4444' },
  { name: 'Respiratory', value: 18, color: '#3B82F6' },
  { name: 'Oncology', value: 15, color: '#8B5CF6' },
  { name: 'Endocrine', value: 12, color: '#F59E0B' },
  { name: 'Orthopedic', value: 10, color: '#10B981' },
  { name: 'Other', value: 23, color: '#6B7280' },
];

export const mockNotifications: Notification[] = [
  {
    id: 'N001',
    title: 'Critical Alert — P001',
    body: 'Eleanor Whitfield\'s heart rate has exceeded 110 bpm. Immediate review required.',
    time: '2 min ago',
    read: false,
    type: 'critical',
  },
  {
    id: 'N002',
    title: 'Lab Results Ready',
    body: 'Blood panel results for Marcus Chen (P002) are now available.',
    time: '18 min ago',
    read: false,
    type: 'info',
  },
  {
    id: 'N003',
    title: 'Patient Discharged',
    body: 'Daniel Kim (P008) has been successfully discharged from Orthopedics.',
    time: '1 hr ago',
    read: false,
    type: 'success',
  },
  {
    id: 'N004',
    title: 'Medication Low Stock',
    body: 'Metformin 500mg stock is below threshold. Reorder recommended.',
    time: '3 hr ago',
    read: true,
    type: 'warning',
  },
  {
    id: 'N005',
    title: 'ICU Bed Available',
    body: 'Pulmonology ICU bed #4 is now available for critical admissions.',
    time: '5 hr ago',
    read: true,
    type: 'info',
  },
];
